package com.selenium.util.enums;

import com.selenium.util.KEY;

public enum AppUrl implements BaseAppUrl {
	IPROPORTAL(KEY.IPRO_PORTAL), MEMBERSPORTAL(KEY.MEMBERS_PORTAL_URL), ADMINPORTAL(KEY.ADMIN_PORTAL_URL), PURCHASEPORTAL(KEY.PURCHASE_URL),
	PURCHASE_ACTIVATION_PORTAL(KEY.PURCHASE_ACTIVATE_URL), MEMBER_ACTIVATE_ENV_URL(KEY.MEMBER_ACTIVATE_ENV_URL),
	PROVIDER_PORTAL(KEY.PROVIDER_ENV_URL), CUSTOMERSERVICEPORTAL(KEY.CUSTOMER_SERVICE_PORTAL_URL),
	SMILE_HEALTH_PORTAL(KEY.SMILE_HEALTH_PORTAL_URL), GWC_PORTAL(KEY.GWC_URL),
	OBP_AMIN_UPLOAD_URL(KEY.OBP_AMIN_UPLOAD_URL), OBP_URL(KEY.OBP_URL);

	private final String keyName;

	AppUrl(final String keyName) {
		this.keyName = keyName;
	}

	@Override
	public String toString() {
		return keyName;
	}
}
